services:
  - type: web
    name: telegram-catalog-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
